gymlog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^$', 'gymlog.views.home', name='home'),
    url(r'day/(?P<slug>[-\w]+)/$', 'gymlog.views.day', name='day'),
    url(r'exercise/(?P<slug>[-\w]+)/$', 'gymlog.views.exercise', name='exercise'),

    url(r'thanks/$', 'gymlog.views.form_success', name='form_success'),

    url(r'dev/$', 'gymlog.views.dev', name='dev'),
    )

pullups/urls.py
__author__ = 'clint'
from django.conf.urls import patterns, include, url
from views import *

urlpatterns = patterns('',

    url(r'^$', home, name='home'),
    url(r'^view_history/$', view_history, name='view_history'),
    url(r'^graph/$', graph, name='graph'),
    url(r'^to_do/$', to_do, name='to_do'),
    )

youthinasia/urls.py
from django.conf.urls import patterns, include, url
from youthinasia.views import hello, current_datetime, hours_ahead, form_page, display_meta, thanks
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Admin and testing
    url(r'^$', hello),
    (r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello, name='hello'),
    url(r'^time/$', current_datetime, name='time'),
    url(r'^time/plus/(\d{1,2})$', hours_ahead),
    url(r'^form/$', form_page, name='form'),
    url(r'^thanks/$', thanks),
    url(r'^meta/$', display_meta, name='meta'),


    # Other apps
    url(r'^gallery/',include('gallery.urls', namespace='gallery')),
    url(r'^battleship/$', include('battleship.urls', namespace='battleship')),
    url(r'^pullups/', include('pullups.urls', namespace='pullups')),
    url(r'^gymlog/', include('gymlog.urls', namespace='gymlog')),
) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

pullups/models.py
from django.db import models
from django.core.exceptions import ValidationError

from datetime import datetime

def is_positive(value):
    if value >= 0:
        raise ValidationError(u'%s is not an even number' % value)

CHOICES = (('M','Morning'),('D','Day'),('N','Night'))
class Pullup(models.Model):
    first_set = models.IntegerField(validators=[is_positive])
    second_set = models.IntegerField()
    third_set = models.IntegerField()
    average = models.FloatField()
    total = models.IntegerField()
    time_of_day = models.CharField(max_length=1, choices=CHOICES)
    date = models.DateField(default=datetime.now())
    notes = models.TextField(blank=True)

    def __unicode__(self):
        return str(self.date)

    def save(self, *args, **kwargs):
        self.average = float((self.first_set + self.second_set + self.third_set) / 3)
        self.total = self.first_set + self.second_set + self.third_set
        super(Pullup, self).save(*args, **kwargs)

pullups/forms.py
__author__ = 'clint'

from pullups.models import Pullup

from django import forms

class PullupForm(forms.ModelForm):
    class Meta:
        model = Pullup
        exclude = ('average','total',)

pullups/views.py
from django.shortcuts import render
from pullups.forms import PullupForm
from pullups.models import Pullup



def home(request):
    if(request.GET.get('delete_btn')):
        Pullup.objects.all().delete()

    if request.method == 'POST':
        form = PullupForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = PullupForm()
    return render(request, 'pullups/home.html', {'form': form})

def view_history(request):
    if(request.GET.get('delete_btn')):
        Pullup.objects.all().delete()
    history = Pullup.objects.all()
    return render(request, 'pullups/view_history.html', {'history': history})

def graph(request):
    if(request.GET.get('delete_btn')):
        Pullup.objects.all().delete()
    history = Pullup.objects.all()
    return render(request, 'pullups/graph.html', {'history': history})

def to_do(request):
    return render(request, 'pullups/to_do.html')

templates/pullups/base.html
<html>
<head>
<title> {% block title %} pullup tracker {% endblock %} </title>
</head>

<body>
<div id="container">

<div id="header">
    <h1>pullups tracker</h1>
</div>

<div id="menu">
    <a href="{% url 'pullups:home' %}">home</a> |
    <a href="{% url 'pullups:view_history' %}">view history</a> |
    <a href="{% url 'pullups:graph' %}">graph it</a> |
    <a href="{% url 'pullups:to_do' %}">to do</a> |
    <form action="#" method="get">
    <input type="submit" value="Delete" name="delete_btn">
    </form>
</form>
</div>

<div id="content">
{% block content %} {% endblock %}
</div>

</div>
</body>

</html>

templates/pullups/delete.html
{% extends 'pullups/base.html' %}

{% block content %}

hey yer shit's been deleted!

{% endblock %}

templates/pullups/graph.html
{% extends 'pullups/base.html' %}

{% block content %}

graff it


{% endblock %}

templates/pullups/home.html
{% extends 'pullups/base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

templates/pullups/to_do.html
{% extends 'pullups/base.html' %}

{% block content %}

to do list
<li><strike>add total to model</strike></li>
<li>add graph</li>
<li>form constraints (testing?)</li>
<li>improve shitty view table</li>

{% endblock %}

templates/pullups/view_history.html
{% extends 'pullups/base.html' %}

{% block content %}

<table border = 1>
    <tr>
        <td>1st</td>
        <td>2nd</td>
        <td>3rd</td>
        <td>Avg</td>
        <td>Total</td>
        <td>Time</td>
        <td>Date</td>
        <td>Notes</td>
    </tr>
{% for item in history %}
    <tr>
        <td> {{ item.first_set }} </td>
        <td> {{ item.second_set }} </td>
        <td> {{ item.third_set }} </td>
        <td> {{ item.average }} </td>
        <td> {{ item.total }} </td>
        <td> {{ item.time_of_day }} </td>
        <td> {{ item.date }} </td>
        <td> {{ item.notes }} </td>
     </tr>
{% endfor %}
</table>
{% endblock %}