gallery/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'gallery.views.home', name='home'),
    url(r'^addgallery/$', 'gallery.views.addgallery', name='addgallery'),
    url(r'^(?P<slug>.+)/$', 'gallery.views.gallery', name='view'),
)

gymlog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^$', 'gymlog.views.home', name='home'),
    url(r'day/(?P<slug>[-\w]+)/$', 'gymlog.views.day', name='day'),
    url(r'exercise/(?P<slug>[-\w]+)/$', 'gymlog.views.exercise', name='exercise'),

    url(r'thanks/$', 'gymlog.views.form_success', name='form_success'),

    url(r'dev/$', 'gymlog.views.dev', name='dev'),
    )

youthinasia/urls.py
from django.conf.urls import patterns, include, url
from youthinasia.views import hello, current_datetime, hours_ahead, form_page, display_meta, thanks
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Admin and testing
    url(r'^$', hello),
    (r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello, name='hello'),
    url(r'^time/$', current_datetime, name='time'),
    url(r'^time/plus/(\d{1,2})$', hours_ahead),
    url(r'^form/$', form_page, name='form'),
    url(r'^thanks/$', thanks),
    url(r'^meta/$', display_meta, name='meta'),


    # Other apps
    url(r'^gallery/',include('gallery.urls', namespace='gallery')),
    url(r'^battleship/$', include('battleship.urls', namespace='battleship')),
    url(r'^pullups/', include('pullups.urls', namespace='pullups')),
    url(r'^gymlog/', include('gymlog.urls', namespace='gymlog')),
) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

gallery/models.py
from django.db import models
from django.template.defaultfilters import slugify

from datetime import datetime

# Create your models here.

class Gallery(models.Model):
    name = models.CharField(max_length=200)
    create_date = models.DateTimeField('date published', default=datetime.now())
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Gallery, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Image(models.Model):
    gallery = models.ForeignKey(Gallery)
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    thumb = models.CharField(max_length=200)
    notes = models.CharField(max_length=200)
    create_date = models.DateTimeField('date published', default=datetime.now)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.thumb = self.name[:self.name.rfind('.')] + '_thumb' + self.name[self.name.rfind('.'):]
        super(Image, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

gallery/forms.py
__author__ = 'clint'

from gallery.models import Gallery, Image

from django import forms

class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['name']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['name', 'notes']

gallery/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from gallery.models import Gallery, Image
from gallery.forms import GalleryForm

from utils import gallery_fuctions as gfunc

def home(request):
    galleries = Gallery.objects.all()
    return render(request, 'gallery/home.html', {'galleries': galleries})

def addgallery(request):

    if request.method == 'POST':
        form = GalleryForm(request.POST)
        if form.is_valid():
            gallery = form.save()
            gfunc.create_folder(gallery.slug)

    else:
        form = GalleryForm()
    return render(request, 'gallery/addgallery.html', {'form': form})

def gallery(request, slug):
    g = Gallery.objects.get(slug = slug)
    images = g.image_set.all()

    if len(images) == 0:
        return render(request, 'gallery/gallery.html', {'images': images, 'warning': "No Images!"})
    else:
        return render(request, 'gallery/gallery.html', {'images': images})

templates/gallery/addgallery.html
{% extends 'gallery/base.html' %}

{% block content %}

Add a new gallery!

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input value="Submit" type="submit">
</form>

{% endblock %}

templates/gallery/base.html
<html>
<head>
    <title>Image Galleries</title>
</head>
<body>
<h2><a href="{% url 'gallery:home' %}">Home</a></h2>

<div id="options">
    <ul>
        <a href="">Upload an image</a> |
        <a href="{% url 'gallery:addgallery' %}">Create New Gallery</a> |
        <a href="{% url 'gallery:home' %}">View Galleries</a>
    </ul>
</div>

<div id="content">
{% block content %} {% endblock %}
</div>

</body>
</html>

templates/gallery/gallery.html
{% extends "gallery/home.html" %}
{% load staticfiles %}

{% block content %}
Yo here goes the pics!

        {{ name }}

{%  if warning %}
    {{ warning }}
{% endif %}

{% for i in images %}
      <li>
          <img src = "{% static i.thumb %}"/>
          <a href = "{% static i %}">{{ i.notes }}</a>

      </li>
{% endfor %}

{% endblock %}

templates/gallery/home.html
{% extends "gallery/base.html" %}


{% block content %}

{% for g in galleries %}
      <li>
          <a href = "{{ g.slug }}">{{ g }}</a>
      </li>
{% endfor %}

{% endblock %}