gymlog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',

    url(r'^$', 'gymlog.views.home', name='home'),
    url(r'day/(?P<slug>[-\w]+)/$', 'gymlog.views.day', name='day'),
    url(r'exercise/(?P<slug>[-\w]+)/$', 'gymlog.views.exercise', name='exercise'),

    url(r'thanks/$', 'gymlog.views.form_success', name='form_success'),

    url(r'dev/$', 'gymlog.views.dev', name='dev'),
    )

youthinasia/urls.py
from django.conf.urls import patterns, include, url
from youthinasia.views import hello, current_datetime, hours_ahead, form_page, display_meta, thanks
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Admin and testing
    url(r'^$', hello),
    (r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello, name='hello'),
    url(r'^time/$', current_datetime, name='time'),
    url(r'^time/plus/(\d{1,2})$', hours_ahead),
    url(r'^form/$', form_page, name='form'),
    url(r'^thanks/$', thanks),
    url(r'^meta/$', display_meta, name='meta'),


    # Other apps
    url(r'^gallery/',include('gallery.urls', namespace='gallery')),
    url(r'^battleship/$', include('battleship.urls', namespace='battleship')),
    url(r'^pullups/', include('pullups.urls', namespace='pullups')),
    url(r'^gymlog/', include('gymlog.urls', namespace='gymlog')),
) + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

gymlog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError

from datetime import datetime

def is_positive(value):
    if value <= 0:
        raise ValidationError(u'%s is not a positive integer.' % value)

'''
A routine is a set of Days, For example, Push-Pull-Legs, or A-B-A
Should have a good description (hypertrophy, strength, etc.)
(to be added later)
'''
class Routine(models.Model):
    pass

'''
A Day is a set of Exercises. For example, "leg day", or simply "A"
in an "ABxABxx" workout.
'''
class Day(models.Model):
    name = models.CharField(max_length=50)
    date_created = models.DateField(default=datetime.now())
    slug = models.SlugField(blank=True, editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Day, self).save(*args, **kwargs)

class Exercise(models.Model):
    days = models.ManyToManyField(Day)
    name = models.CharField(max_length=50)
    date_created = models.DateField(default=datetime.now())
    slug = models.SlugField(blank=True, editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Exercise, self).save(*args, **kwargs)

class Instance(models.Model):
    name = models.CharField(max_length=50, blank=True, editable=False)
    exercise = models.ForeignKey(Exercise)
    weight = models.FloatField()
    reps = models.IntegerField(validators=[is_positive])
    sets = models.IntegerField(validators=[is_positive])
    date = models.DateField(default=datetime.now())

    def save(self, *args, **kwargs):
        self.name = '<Instance ID #%s>' % (self.pk)
        super(Instance, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

gymlog/forms.py
from gymlog.models import Instance

from django import forms

class InstanceForm(forms.ModelForm):
    class Meta:
        model = Instance
        exclude = ('name','exercise','date',)

gymlog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from gymlog.models import Day, Exercise, Instance
from gymlog.forms import InstanceForm

import os

def dev(request):
    '''
    Things useful for development; only displayed in DEBUG mode
    '''
    from youthinasia import settings

    items = []
    db = settings.DATABASES

    items.append(db)
    items.append(os.getcwd().split())

    return render(request, 'gymlog/dev.html', {'items': items})

def home(request):
    '''
    List all the days in the current Routine.
    '''
    days = Day.objects.all()

    return render(request, 'gymlog/home.html', {'days': days})

def day(request, slug):
    '''
    Show all of the exercises in a particular day
    '''
    day = get_object_or_404(Day, slug=slug)
    exercises = day.exercise_set.all()
    return render(request, 'gymlog/day_details.html', {'exercises': exercises})

def exercise(request, slug):
    '''
    Splash page for an exercise, shows the most recent entry and a form for the next entry.
    '''
    exercise = get_object_or_404(Exercise, slug=slug)

    # A little history to show
    history = Instance.objects.filter(exercise_id = exercise.id)

    # Form
    if request.method == 'POST':
        form = InstanceForm(request.POST)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.exercise_id = exercise.id
            instance.save()
            url = reverse('gymlog:form_success', args=())
            return HttpResponseRedirect(url)
    else:
        form = InstanceForm()
    return render(request, 'gymlog/exercise_form.html',
                  {'form': form,
                   'exercise': exercise,
                   'history': history})

def form_success(request):
    return render(request, 'gymlog/form_success.html')

templates/gymlog/base.html
<html>
<head>
<title> {% block title %} gym log {% endblock %} </title>
</head>

<body>
<div id="container">

<div id="header">
    <h1>gym log</h1>
</div>

<div id="menu">
    <a href="{% url 'gymlog:home' %}">home</a> |
    <a href="{% url 'gymlog:dev' %}">dev stuff</a> |
</div>

<div id="content">
{% block content %} {% endblock %}
</div>

</div>
</body>

</html>

templates/gymlog/day_details.html
{% extends 'gymlog/base.html' %}

{% block content %}

<table>
    {% for exercise in exercises %}
    <tr>
        <td>
            <a href="{% url 'gymlog:exercise' exercise.slug %}"> {{ exercise.name }} </a>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/gymlog/dev.html
{% extends 'gymlog/base.html' %}

{% block content %}

{% for item in items %}
    <li>{{ item }}</li>
{% endfor %}

{% endblock %}

templates/gymlog/exercise_form.html
{% extends 'gymlog/base.html' %}

{% block content %}

<h2>{{ exercise.name }}</h2>

<div id="form">
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
</div>

<div id="history">
    <table>
        {% for item in history %}
        <tr>
            <td>{{ item.weight }}</td>
            <td>{{ item.sets }}</td>
            <td>{{ item.reps }}</td>
            <td>{{ item.date }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/gymlog/form_success.html
{% extends 'gymlog/base.html' %}

{% block content %}
 thxn

{{ test }}

{% endblock %}

templates/gymlog/home.html
{% extends 'gymlog/base.html' %}

{% block content %}

<table>
    {% for day in days %}
    <tr>
        <td>
            <a href="{% url 'gymlog:day' day.slug %}">{{ day.name }}</a>
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}